name: flutter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-android:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
          KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: echo $KEY_JKS > android/key.jks && ls -l android
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
          KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: echo $KEY_JKS > android/key.jks && flutter build apk
      - uses: actions/upload-artifact@v2
        with:
          name: ninety9names.apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build web
      - run: |
          cd build
          tar -czf ninety9names_web.tar.gz web
      - uses: actions/upload-artifact@v2
        with:
          name: ninety9names_web.tar.gz
          path: build/ninety9names_web.tar.gz
